name: Netherworld EXP Tracker

on:
  workflow_dispatch:
    inputs:
      dungeon:
        description: Dungeon oder Farmgebiet auswählen
        required: true
        type: choice
        options:
          - UG PP
          - UG
          - CV
          - UG LM
          - UG Moon
          - Soulhort
          - Hellmouth
          - ROA
          - HROA
          - DD
          - Circus
          - Keilerspots (Farm)
          - Mino (Farm)
          - Unicorn (Farm)
          - DT (Farm)
          - WD (Farm)
      stage:
        description: Stage Zahl 1 bis 20 (oder leer bei Farm)
        required: false
        type: number
      difficulty:
        description: Schwierigkeit
        required: true
        type: choice
        options:
          - Easy
          - Normal
          - Hard
          - Extreme
      spot:
        description: Konkreter Spot innerhalb des Dungeons oder Farmgebiets
        required: true
        type: string
      party_type:
        description: Partytyp
        required: true
        type: choice
        options:
          - Solo
          - Duo
          - Trio
          - DP
      note:
        description: Optionale Notiz
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 70

    permissions:
      contents: write

    concurrency:
      group: netherworld-exp-tracker
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Tracking starten
        env:
          DUNGEON: ${{ github.event.inputs.dungeon }}
          STAGE: ${{ github.event.inputs.stage }}
          DIFFICULTY: ${{ github.event.inputs.difficulty }}
          SPOT: ${{ github.event.inputs.spot }}
          PARTY_TYPE: ${{ github.event.inputs.party_type }}
          NOTE: ${{ github.event.inputs.note }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python scripts/exp_tracker.py \
            --dungeon "$DUNGEON" \
            --stage "${STAGE:-0}" \
            --difficulty "$DIFFICULTY" \
            --spot "$SPOT" \
            --party-type "$PARTY_TYPE" \
            --note "${NOTE:-}"

      - name: Änderungen committen
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          add: "data/*.csv reports/*.md"
          message: "EXP Tracking Lauf gespeichert"
          default_author: github_actions
